name: Update Release

on:
  push:
    branches:
      - main

jobs:
  update-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating/updating releases

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .zip file
      run: zip -r profiles.zip ./filament ./machine ./process

    - name: Create/Update Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: profiles-latest
        name: Latest Profiles Release
        body: |
          This release includes the latest configuration profiles for the 3D printers at 3DprintFIT lab. Download the profiles.zip and import it into OrcaSlicer as described in the README.
        files: profiles.zip
        make_latest: true 